// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Country = "Denmark",
                            Description = "A modern hotel in the heart of Copenhagen.",
                            ImageUrl = "/images/Copenhagen5.jpg",
                            Name = "Hotel Copenhagen"
                        },
                        new
                        {
                            HotelId = 2,
                            Country = "Denmark",
                            Description = "A cozy hotel in Aarhus.",
                            ImageUrl = "/images/Aarhus.jpg",
                            Name = "Hotel Aarhus"
                        },
                        new
                        {
                            HotelId = 3,
                            Country = "Germany",
                            Description = "An upscale hotel near Brandenburg Gate.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Berlin"
                        },
                        new
                        {
                            HotelId = 4,
                            Country = "Germany",
                            Description = "A charming hotel in Munich.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Munich"
                        },
                        new
                        {
                            HotelId = 5,
                            Country = "France",
                            Description = "A romantic hotel with views of the Eiffel Tower.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Paris"
                        },
                        new
                        {
                            HotelId = 6,
                            Country = "France",
                            Description = "A beautiful hotel in Lyon.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Lyon"
                        },
                        new
                        {
                            HotelId = 7,
                            Country = "Italy",
                            Description = "A charming hotel in the city center.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Rome"
                        },
                        new
                        {
                            HotelId = 8,
                            Country = "Italy",
                            Description = "A stylish hotel in Milan.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Milan"
                        },
                        new
                        {
                            HotelId = 9,
                            Country = "Spain",
                            Description = "A vibrant hotel near the beach.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Barcelona"
                        },
                        new
                        {
                            HotelId = 10,
                            Country = "Spain",
                            Description = "A luxurious hotel in Madrid.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Madrid"
                        },
                        new
                        {
                            HotelId = 11,
                            Country = "UK",
                            Description = "A luxurious hotel in the capital.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel London"
                        },
                        new
                        {
                            HotelId = 12,
                            Country = "UK",
                            Description = "A modern hotel in Manchester.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Manchester"
                        },
                        new
                        {
                            HotelId = 13,
                            Country = "USA",
                            Description = "A stylish hotel in the city.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel New York"
                        },
                        new
                        {
                            HotelId = 14,
                            Country = "USA",
                            Description = "A luxurious hotel in Los Angeles.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Los Angeles"
                        },
                        new
                        {
                            HotelId = 15,
                            Country = "Canada",
                            Description = "A modern hotel in the heart of the city.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Toronto"
                        },
                        new
                        {
                            HotelId = 16,
                            Country = "Canada",
                            Description = "A beautiful hotel in Vancouver.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Vancouver"
                        },
                        new
                        {
                            HotelId = 17,
                            Country = "Australia",
                            Description = "A luxury hotel with views of the harbor.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Sydney"
                        },
                        new
                        {
                            HotelId = 18,
                            Country = "Australia",
                            Description = "A stylish hotel in Melbourne.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Melbourne"
                        },
                        new
                        {
                            HotelId = 19,
                            Country = "Japan",
                            Description = "A high-tech hotel in the city.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Tokyo"
                        },
                        new
                        {
                            HotelId = 20,
                            Country = "Japan",
                            Description = "A traditional hotel in Kyoto.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Kyoto"
                        },
                        new
                        {
                            HotelId = 21,
                            Country = "Brazil",
                            Description = "A beachfront hotel in Brazil.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Rio de Janeiro"
                        },
                        new
                        {
                            HotelId = 22,
                            Country = "Brazil",
                            Description = "A modern hotel in Sao Paulo.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Sao Paulo"
                        },
                        new
                        {
                            HotelId = 23,
                            Country = "China",
                            Description = "A historical hotel in China.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Beijing"
                        },
                        new
                        {
                            HotelId = 24,
                            Country = "China",
                            Description = "A luxurious hotel in Shanghai.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Shanghai"
                        },
                        new
                        {
                            HotelId = 25,
                            Country = "India",
                            Description = "A luxurious hotel in India.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Mumbai"
                        },
                        new
                        {
                            HotelId = 26,
                            Country = "India",
                            Description = "A modern hotel in Delhi.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Delhi"
                        },
                        new
                        {
                            HotelId = 27,
                            Country = "Russia",
                            Description = "A stylish hotel in the capital.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Moscow"
                        },
                        new
                        {
                            HotelId = 28,
                            Country = "Russia",
                            Description = "A beautiful hotel in Saint Petersburg.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Saint Petersburg"
                        },
                        new
                        {
                            HotelId = 29,
                            Country = "South Africa",
                            Description = "A hotel with stunning views.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Cape Town"
                        },
                        new
                        {
                            HotelId = 30,
                            Country = "South Africa",
                            Description = "A modern hotel in Johannesburg.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Johannesburg"
                        },
                        new
                        {
                            HotelId = 31,
                            Country = "Egypt",
                            Description = "A hotel near the pyramids.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Cairo"
                        },
                        new
                        {
                            HotelId = 32,
                            Country = "Egypt",
                            Description = "A beautiful hotel in Alexandria.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Alexandria"
                        },
                        new
                        {
                            HotelId = 33,
                            Country = "Argentina",
                            Description = "A vibrant hotel in Argentina.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Buenos Aires"
                        },
                        new
                        {
                            HotelId = 34,
                            Country = "Argentina",
                            Description = "A charming hotel in Cordoba.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Cordoba"
                        },
                        new
                        {
                            HotelId = 35,
                            Country = "Mexico",
                            Description = "A modern hotel in the capital.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Mexico City"
                        },
                        new
                        {
                            HotelId = 36,
                            Country = "Mexico",
                            Description = "A beachfront hotel in Cancun.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Cancun"
                        },
                        new
                        {
                            HotelId = 37,
                            Country = "Turkey",
                            Description = "A historic hotel in the city.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Istanbul"
                        },
                        new
                        {
                            HotelId = 38,
                            Country = "Turkey",
                            Description = "A modern hotel in Ankara.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Ankara"
                        },
                        new
                        {
                            HotelId = 39,
                            Country = "Greece",
                            Description = "A hotel with stunning views of the Acropolis.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Athens"
                        },
                        new
                        {
                            HotelId = 40,
                            Country = "Greece",
                            Description = "A charming hotel in Thessaloniki.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Thessaloniki"
                        },
                        new
                        {
                            HotelId = 41,
                            Country = "Portugal",
                            Description = "A charming hotel in Portugal.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Lisbon"
                        },
                        new
                        {
                            HotelId = 42,
                            Country = "Portugal",
                            Description = "A beautiful hotel in Porto.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Hotel Porto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
